# Generated by Django 5.0.5 on 2025-01-17 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='district/')),
            ],
        ),
        migrations.CreateModel(
            name='Numberofvoters1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_vote', models.IntegerField(blank=True, null=True)),
                ('station_vote', models.IntegerField(blank=True, null=True)),
                ('advance_vote', models.IntegerField(blank=True, null=True)),
                ('total_vote', models.IntegerField(blank=True, null=True)),
                ('constituency', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('election_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='party_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Khayine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.district')),
            ],
        ),
        migrations.CreateModel(
            name='Township',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('khayine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.khayine')),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='constituency/')),
                ('detail_file', models.FileField(blank=True, null=True, upload_to='constituency/details')),
                ('hlutdaw', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.district')),
                ('khayine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.khayine')),
                ('township', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.township')),
            ],
        ),
        migrations.CreateModel(
            name='Valid_vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_vote', models.IntegerField(blank=True, null=True)),
                ('advance_vote', models.IntegerField(blank=True, null=True)),
                ('total_vote', models.IntegerField(blank=True, null=True)),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('candidate', models.CharField(blank=True, max_length=200, null=True)),
                ('party', models.CharField(blank=True, max_length=200, null=True)),
                ('hlutdaw', models.CharField(blank=True, max_length=200, null=True)),
                ('election_year', models.IntegerField(blank=True, null=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.constituency')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.district')),
            ],
        ),
    ]
