# Generated by Django 5.0.5 on 2025-01-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valid_vote',
            name='win_lose',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
