# Generated by Django 5.1.1 on 2025-01-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_valid_vote_win_lose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
